# Generated by Django 6.0.4 on 2026-07-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0002_produto_itempedido_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="bling_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="bling_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="bling_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
